export const ADD_NEW_GROUP_REQUEST = "ADD_NEW_GROUP_REQUEST";
export const ADD_NEW_GROUP_SUCCSESS ="ADD_NEW_GROUP_SUCCSESS";
export const ADD_NEW_GROUP_FAILURE = "ADD_NEW_GROUP_FAILURE";

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST";
export const ADD_CUSTOMER_SUCCSESS ="ADD_CUSTOMER_SUCCSESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";

