export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCSESS = "CREATE_PRODUCT_SUCCSESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCSESS = "ADD_STAFF_SUCCSESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCSESS = "FETCH_SUCCSESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const STAFF_GROUP_REQUEST = "STAFF_GROUP_REQUEST";
export const STAFF_GROUP_SUCCSESS = "STAFF_GROUP_SUCCSESS";
export const STAFF_GROUP_FAILURE = "STAFF_GROUP_FAILURE";

export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCSESS = "ALL_CUSTOMER_SUCCSESS";
export const ALL_CUSTOMER_FAILURE = "ALL_CUSTOMER_FAIL";

export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCSESS = "ALL_CATEGORY_SUCCSESS";
export const ALL_CATEGORY_FAILURE = "ALL_CATEGORY_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
