export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCSESS = "CREATE_PRODUCT_SUCCSESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCSESS = "ADD_STAFF_SUCCSESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";
